### ISSUE TITLE
Git repositories without any commits give “Bad revision 'HEAD'” error

### ISSUE THREAD

**Issue by sindrenm** [timkurvers/waddup#10]
When running waddup on a repository that doesn't have any commits yet I get an error message like the following:

```
fatal: bad default revision 'HEAD'
```

Not really sure if I could call it a bug though, as this is actually an error message that Git gives back from the `git log` command, but it would be nice to catch that, I guess. :smile: 

Cheers!

**Comment by timkurvers** [comment]
Good catch!
